meta:
  environment: neo4j-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: neo4j
    networks:
      - name: neo4j1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: neo4j1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.33.0/30
    reserved:
    - 10.244.33.1
    static:
    - 10.244.33.2

  - cloud_properties:
      name: random
    range: 10.244.33.4/30
    reserved:
    - 10.244.33.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.33.8/30
    reserved:
    - 10.244.33.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.33.12/30
    reserved:
    - 10.244.33.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.33.16/30
    reserved:
    - 10.244.33.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.33.20/30
    reserved:
    - 10.244.33.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.33.24/30
    reserved:
    - 10.244.33.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.33.28/30
    reserved:
    - 10.244.33.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.33.32/30
    reserved:
    - 10.244.33.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.33.36/30
    reserved:
    - 10.244.33.37
    static: []
