groups:
- name: build
  jobs:
  - testflight
  - rc
  - shipit
- name: version
  jobs:
  - patch
  - minor
  - major
- name: ci_image
  jobs:
  - build-task-image

jobs:
- name: build-task-image
  public: true
  serial: true
  plan:
  - get: git-boshrelease
    trigger: true
  - put: docker-image
    params:
      build: git-boshrelease/ci/ci_image

- name: testflight
  public: true
  serial: true
  plan:
  - do:
    - aggregate:
      - get: neo4j-boshrelease
        resource: git-neo4j-boshrelease
      - get: git-neo4j-boshrelease-release-changes
        trigger: true
    - task: create-release-and-deploy
      config:
        platform: linux
        image: {{docker-hub-task-image}}
        inputs:
        - {name: neo4j-boshrelease}
        run:
          path: ./neo4j-boshrelease/ci/scripts/create_release_and_deploy.sh
          args: []
        params:
          bosh_target: {{bosh-lite-build-target}}
          bosh_username: {{bosh-lite-build-username}}
          bosh_password: {{bosh-lite-build-password}}
          bosh_deployment_name: {{bosh-lite-build-deployment-name}}

- name: rc
  public: true
  plan:
  - aggregate:
    - get: boshrelease
      resource: git-neo4j-boshrelease
      passed: [testflight]
      trigger: true
    - get: version
      trigger: false
      params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: patch
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: patch}
  - put: version
    params: {file: version/number}

- name: minor
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: major
  public: true
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: major}
  - put: version
    params: {file: version/number}

- name: shipit
  public: true
  serial: true
  plan:
  - aggregate:
    - get: version
      passed: [rc]
      params: {bump: final}
    - get: boshrelease
      resource: git-neo4j-boshrelease
      passed: [rc]
  - task: create-final-release
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: boshrelease, path: neo4j-boshrelease}
      - {name: version}
      outputs:
      - {name: create-final-release, path: output}
      run:
        path: ./neo4j-boshrelease/ci/scripts/shipit.sh
        args: []
      params:
        release_name: "neo4j BOSH Release"
        bosh_target: {{bosh-lite-build-target}}
        bosh_username: {{bosh-lite-build-username}}
        bosh_password: {{bosh-lite-build-password}}
        bosh_deployment_name: {{bosh-lite-build-deployment-name}}
        aws_access_key_id: {{boshrelease-aws-access-key-id}}
        aws_secret_access_key: {{boshrelease-aws-secret-access-key}}
        promotion_branch: concourse-0.72
        output_dir: ../output/neo4j-boshrelease
  - put: git-neo4j-boshrelease
    params:
      repository: create-final-release/neo4j-boshrelease
      rebase: true
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: final-release
      params:
        from: create-final-release/neo4j-boshrelease/releases/neo4j/neo4j-(.*).tgz
        to: neo4j-boshrelease/
    - put: github-final-release
      params:
        name: create-final-release/neo4j-boshrelease/release/name
        tag: create-final-release/neo4j-boshrelease/release/tag
        body: create-final-release/neo4j-boshrelease/release/notes.md
        globs: [create-final-release/neo4j-boshrelease/releases/neo4j/neo4j-*.tgz]

resources:
- name: version
  type: semver
  source:
    key: current-version
    bucket: {{pipeline-aws-bucket}}
    access_key_id: {{pipeline-aws-access-key-id}}
    secret_access_key: {{pipeline-aws-secret-access-key}}
    initial_version: 0.0.0

- name: git-neo4j-boshrelease
  type: git
  source:
    uri: {{pipeline-git-repo}}
    branch: {{pipeline-branch}}

- name: git-neo4j-boshrelease-release-changes
  type: git
  source:
    uri: {{pipeline-git-repo}}
    branch: {{pipeline-branch}}
    paths:
      - src/**/*
      - jobs/**/*
      - packages/**/*
      - config/blobs.yml
      - .final_builds/**/*
      - templates/**/*
      - .gitmodules

- name: github-final-release
  type: github-release
  source:
    user: hybris
    repository: neo4j-boshrelease
    access_token: {{github-access-token}}

- name: final-release
  type: s3
  source:
    bucket: {{boshrelease-aws-bucket}}
    regexp: neo4j-boshrelease/neo4j-(.*).tgz
    access_key_id: {{boshrelease-aws-access-key-id}}
    secret_access_key: {{boshrelease-aws-secret-access-key}}

- name: git-boshrelease
  type: git
  source:
    uri: {{pipeline-git-repo}}
    branch: {{pipeline-branch}}
    paths: [ci/ci_image/*]

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-hub-task-image}}
